### ISSUE TITLE
wrong argument type GLib::Param::Object (expected Data)

### ISSUE THREAD

**Issue by tomasc** [jcupitt/ruby-vips#110] opened 2017-06-10 15:32 UTC
experiencing this occasionally:

```
wrong argument type GLib::Param::Object (expected Data)

ruby-vips (1.0.5) lib/vips/argument.rb:24:in `blurb'
ruby-vips (1.0.5) lib/vips/argument.rb:24:in `initialize'
ruby-vips (1.0.5) lib/vips/operation.rb:15:in `new'
ruby-vips (1.0.5) lib/vips/operation.rb:15:in `block in get_args'
ruby-vips (1.0.5) lib/vips/operation.rb:15:in `map'
ruby-vips (1.0.5) lib/vips/operation.rb:15:in `get_args'
ruby-vips (1.0.5) lib/vips/call.rb:80:in `find_input'
ruby-vips (1.0.5) lib/vips/call.rb:247:in `invoke'
ruby-vips (1.0.5) lib/vips/call.rb:282:in `call_base'
ruby-vips (1.0.5) lib/vips/image.rb:471:in `new_from_file'
```

**Comment by jcupitt** [comment] 2017-06-16 08:13
Sorry, I don't know :( That sounds like a Ruby goi issue, `blurb` is a property defined by the `gobject-introspection` gem

**Comment by raimondasv** [comment] 2017-07-01 11:12
Experiencing same problems. It happens at random operations with random error messages. Looks like a ruby code is trying to access methods or constants while library is not yet loaded.  It is hard to get debug output in the production - on a 40 core machine it happens time to time at 10K rpm.

It's a multi-threading issue - after switching puma to single thread - errors disappeared completely. 

Having this in puma config
```
on_worker_boot do
  require 'vips'
  Vips.init()
end
```
reduced error count significantly.

After adding mutexes on all Vips operations - it almost went away. But still experiencing it - probably because there parts of the code not guarded by mutex. It's more a mitigation of the problem than a solution.

I guess we have to dig deeper and provide gem creators with more information.

**Comment by jcupitt** [comment] 2017-07-01 11:33
My feeling is that this is likely to be a problem with the gobject-introspection gem that vips uses. 

The underlying libvips library has been though fire and (now, finally) seems to be robustly threadsafe. It's used in huge production systems under very heavy load with (I think) pretty good reliability. The vips gem is rather simple and has no global variables that are modified during operation, so I don't understand how that can be the cause. 

I did notice one weird thing during development: the vips gem had to turn off the GC during a vips operation call or bad things would happen. I've not tested to see if the gobject-introspection gem still has this problem. Could that be related to this threading issue?

I've just done a Lua binding for libvips based on ffi, not gobject-introspection. It was a lot simpler than I expected, and of course it gets rid of a huge and slightly wobbly dependency. Perhaps the true fix for this is to rework ruby-vips on top of ffi instead, which is a depressing thought.

**Comment by jcupitt** [comment] 2017-07-04 15:54
I've made a branch for experimenting with FFI instead of gobject-introspection:

https://github.com/jcupitt/ruby-vips/tree/ffi-experiment

If you run this thing:

https://github.com/jcupitt/ruby-vips/blob/ffi-experiment/ffi/try2.rb

You can create an image, make an operation, and see its arguments. I'll fiddle with it a bit more. 

I don't know anything about ruby-ffi, so if anyone is an expert, please fix my code!

**Comment by jcupitt** [comment] 2017-07-04 15:55
The Lua binding I'm basing this off:

https://github.com/jcupitt/lua-vips

**Comment by tomasc** [comment] 2017-07-12 10:15
thanks @jcupitt I will try to look into this

**Comment by jcupitt** [comment] 2017-07-15 17:27
It passes the test suite: https://github.com/jcupitt/ruby-vips/issues/115

Testing very welcome.

**Comment by tomasc** [comment] 2017-07-15 19:35
@jcupitt would it be a good idea to first add the https://github.com/jcupitt/ruby-vips/pull/114 so that we can test the new setup in production?

**Comment by jcupitt** [comment] 2017-08-22 12:20
ruby-vips 2.0 is in rubygems now and should fix this. Please reopen if it's still broken.

**Closed by jcupitt** 2017-08-22 12:20 UTC
Labels: bug
